# -*- coding: utf-8 -*-
"""aiproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uHj7RuEswW24LvfHZ6xeYxXbuR9Kns25
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import os
import requests # Import the requests library

file_path = 'creditcard.csv'
# Updated download URL as the previous one was giving a 404 error
download_url = 'https://raw.githubusercontent.com/VianneyLefebvre/credit_card_fraud/main/creditcard.csv'

# Check if the dataset exists, if not, download it
if not os.path.exists(file_path):
    print(f"Downloading {file_path} from {download_url}...")
    try:
        response = requests.get(download_url, stream=True)
        response.raise_for_status() # Raise an exception for HTTP errors (4xx or 5xx)
        with open(file_path, 'wb') as f:
            for chunk in response.iter_content(chunk_size=8192):
                f.write(chunk)
        print("Download complete.")
    except requests.exceptions.RequestException as e:
        raise FileNotFoundError(f"Failed to download {file_path}. Please check the URL or your network connection. Error: {e}")

    # Verify file existence after download attempt
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Failed to download {file_path}. Please check the URL or your network connection.")

# 1. Load Data
df = pd.read_csv(file_path)

# 2. Visualize Imbalance
print("Dataset Shape:", df.shape)
counts = df['Class'].value_counts()
print("\nClass Distribution:\n", counts)

plt.figure(figsize=(6, 4))
sns.countplot(x='Class', data=df)
plt.title('Class Imbalance: 0=Legit, 1=Fraud')
plt.yscale('log') # Log scale helps visualize the tiny minority class
plt.savefig('imbalance_plot.png')
plt.show()

# 3. Preprocessing
# We drop 'Time' as it's not useful for general fraud patterns,
# and we scale 'Amount' and V1-V28.
df = df.drop(['Time'], axis=1)

# Split into Features (X) and Target (y)
X = df.drop('Class', axis=1)
y = df['Class']

# Standardize features (Crucial for GANs to converge!)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

# 4. Save the Scaler (we need to inverse transform later)
import joblib
joblib.dump(scaler, 'scaler.pkl')

# 5. Isolate Minority Class for GAN Training (Source 86)
# We only train GANs on the FRAUD data (Class 1)
X_fraud = X_scaled[y == 1]
X_legit = X_scaled[y == 0]

print(f"\nTraining Data for GANs (Fraud Only): {X_fraud.shape}")

# Save processed parts for next steps
X_fraud.to_csv('X_fraud.csv', index=False)
X_legit.to_csv('X_legit.csv', index=False)

#Implementing the Vanilla GAN
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import numpy as np

# 1. Load Data
data = pd.read_csv('X_fraud.csv')
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Convert to PyTorch Tensor
real_data = torch.tensor(data.values, dtype=torch.float32).to(device)
data_dim = real_data.shape[1] # Number of columns (features)

# 2. Define Hyperparameters
NOISE_DIM = 16
LR = 0.001
EPOCHS = 2000  # High number because dataset is tiny (492 rows)
BATCH_SIZE = 64

# 3. Define Vanilla GAN Architecture

# Generator: Takes Noise -> Outputs Fake Data
class Generator(nn.Module):
    def __init__(self):
        super(Generator, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(NOISE_DIM, 32),
            nn.ReLU(),
            nn.Linear(32, 64),
            nn.ReLU(),
            nn.Linear(64, data_dim),
            # No Tanh/Sigmoid at end because we standardized data (can be -ve or +ve)
        )

    def forward(self, x):
        return self.net(x)

# Discriminator: Takes Data -> Outputs Probability (Real vs Fake)
class Discriminator(nn.Module):
    def __init__(self):
        super(Discriminator, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(data_dim, 64),
            nn.LeakyReLU(0.2),
            nn.Linear(64, 32),
            nn.LeakyReLU(0.2),
            nn.Linear(32, 1),
            nn.Sigmoid() # Probability output (0 to 1)
        )

    def forward(self, x):
        return self.net(x)

# Initialize
gen = Generator().to(device)
disc = Discriminator().to(device)

opt_gen = optim.Adam(gen.parameters(), lr=LR)
opt_disc = optim.Adam(disc.parameters(), lr=LR)

criterion = nn.BCELoss() # Binary Cross Entropy Loss

# 4. Training Loop
print("Starting Vanilla GAN Training...")

dataset = torch.utils.data.TensorDataset(real_data)
loader = torch.utils.data.DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

for epoch in range(EPOCHS):
    for batch_idx, (real,) in enumerate(loader):
        batch_size = real.shape[0]

        ### Train Discriminator: max log(D(x)) + log(1 - D(G(z)))
        noise = torch.randn(batch_size, NOISE_DIM).to(device)
        fake = gen(noise)

        disc_real = disc(real).view(-1)
        loss_disc_real = criterion(disc_real, torch.ones_like(disc_real))

        disc_fake = disc(fake.detach()).view(-1)
        loss_disc_fake = criterion(disc_fake, torch.zeros_like(disc_fake))

        loss_disc = (loss_disc_real + loss_disc_fake) / 2
        disc.zero_grad()
        loss_disc.backward()
        opt_disc.step()

        ### Train Generator: min log(1 - D(G(z))) <-> max log(D(G(z)))
        output = disc(fake).view(-1)
        loss_gen = criterion(output, torch.ones_like(output))

        gen.zero_grad()
        loss_gen.backward()
        opt_gen.step()

    if epoch % 500 == 0:
        print(f"Epoch [{epoch}/{EPOCHS}] Loss D: {loss_disc:.4f}, loss G: {loss_gen:.4f}")

# 5. Generate Synthetic Data for Balancing
# We want to generate enough fraud cases to match the majority class roughly
# or at least a significant amount (e.g., 20,000 samples)
num_synthetic = 20000
with torch.no_grad():
    noise = torch.randn(num_synthetic, NOISE_DIM).to(device)
    fake_data = gen(noise).cpu().numpy()

# Save to CSV
df_fake = pd.DataFrame(fake_data, columns=data.columns)
df_fake['Class'] = 1 # Label them as Fraud
df_fake.to_csv('vanilla_gan_fraud.csv', index=False)
print("Finished. Synthetic data saved to 'vanilla_gan_fraud.csv'.")

#Implement WGAN
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import numpy as np

# 1. Load Data
data = pd.read_csv('X_fraud.csv')
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

real_data = torch.tensor(data.values, dtype=torch.float32).to(device)
data_dim = real_data.shape[1]

# 2. Hyperparameters
NOISE_DIM = 16
LR = 0.00005        # WGAN needs lower learning rate
EPOCHS = 2000
BATCH_SIZE = 64
CLIP_VALUE = 0.01   # WGAN Weight clipping
N_CRITIC = 5        # Train critic 5 times for every 1 gen step

# 3. WGAN Architecture

class Generator(nn.Module):
    def __init__(self):
        super(Generator, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(NOISE_DIM, 32),
            nn.ReLU(),
            nn.Linear(32, 64),
            nn.ReLU(),
            nn.Linear(64, data_dim),
        )

    def forward(self, x):
        return self.net(x)

class Critic(nn.Module):
    def __init__(self):
        super(Critic, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(data_dim, 64),
            nn.LeakyReLU(0.2),
            nn.Linear(64, 32),
            nn.LeakyReLU(0.2),
            nn.Linear(32, 1)
            # NO Sigmoid here! WGAN output is unbound.
        )

    def forward(self, x):
        return self.net(x)

# Initialize
gen = Generator().to(device)
critic = Critic().to(device)

# WGAN uses RMSprop usually (Adam can cause instability in WGAN)
opt_gen = optim.RMSprop(gen.parameters(), lr=LR)
opt_critic = optim.RMSprop(critic.parameters(), lr=LR)

# 4. Training Loop
print("Starting WGAN Training...")

dataset = torch.utils.data.TensorDataset(real_data)
loader = torch.utils.data.DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

for epoch in range(EPOCHS):
    for batch_idx, (real,) in enumerate(loader):
        batch_size = real.shape[0]
        real = real.to(device)

        # --- Train Critic ---
        # We train the critic more often than the generator
        for _ in range(N_CRITIC):
            noise = torch.randn(batch_size, NOISE_DIM).to(device)
            fake = gen(noise)

            critic_real = critic(real).reshape(-1)
            critic_fake = critic(fake).reshape(-1)

            # WGAN Loss: -(mean(real) - mean(fake))
            # We want to maximize the gap between real and fake scores
            loss_critic = -(torch.mean(critic_real) - torch.mean(critic_fake))

            critic.zero_grad()
            loss_critic.backward(retain_graph=True)
            opt_critic.step()

            # Clip weights to enforce 1-Lipschitz constraint
            for p in critic.parameters():
                p.data.clamp_(-CLIP_VALUE, CLIP_VALUE)

        # --- Train Generator ---
        # Train Generator only once after N_CRITIC steps
        noise = torch.randn(batch_size, NOISE_DIM).to(device)
        fake = gen(noise)
        critic_fake = critic(fake).reshape(-1)

        # Generator wants to maximize Critic's score for fakes
        loss_gen = -torch.mean(critic_fake)

        gen.zero_grad()
        loss_gen.backward()
        opt_gen.step()

    if epoch % 500 == 0:
        print(f"Epoch [{epoch}/{EPOCHS}] Loss Critic: {loss_critic.item():.4f}, Loss Gen: {loss_gen.item():.4f}")

# 5. Generate Synthetic Data
num_synthetic = 20000
with torch.no_grad():
    noise = torch.randn(num_synthetic, NOISE_DIM).to(device)
    fake_data = gen(noise).cpu().numpy()

# Save
df_fake = pd.DataFrame(fake_data, columns=data.columns)
df_fake['Class'] = 1
df_fake.to_csv('wgan_fraud.csv', index=False)
print("Finished. Synthetic data saved to 'wgan_fraud.csv'.")

import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import numpy as np

# 1. Prepare Data
try:
    data = pd.read_csv('X_fraud.csv')
except:
    data = pd.DataFrame(X_fraud, columns=X.columns)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

real_data = torch.tensor(data.values, dtype=torch.float32).to(device)
data_dim = real_data.shape[1]

# 2. Hyperparameters
NOISE_DIM = 16
LR = 0.0002
EPOCHS = 2000
BATCH_SIZE = 64

# 3. LSGAN Architecture
class LSGAN_Generator(nn.Module):
    def __init__(self):
        super(LSGAN_Generator, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(NOISE_DIM, 32),
            nn.BatchNorm1d(32),
            nn.ReLU(),
            nn.Linear(32, 64),
            nn.BatchNorm1d(64),
            nn.ReLU(),
            nn.Linear(64, data_dim),
        )

    def forward(self, x):
        return self.net(x)

class LSGAN_Discriminator(nn.Module):
    def __init__(self):
        super(LSGAN_Discriminator, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(data_dim, 64),
            nn.LeakyReLU(0.2),
            nn.Linear(64, 32),
            nn.LeakyReLU(0.2),
            nn.Linear(32, 1)
        )

    def forward(self, x):
        return self.net(x)

# Initialize models
ls_gen = LSGAN_Generator().to(device)
ls_disc = LSGAN_Discriminator().to(device)

# Optimizers
opt_gen = optim.Adam(ls_gen.parameters(), lr=LR, betas=(0.5, 0.999))
opt_disc = optim.Adam(ls_disc.parameters(), lr=LR, betas=(0.5, 0.999))

# Loss Function
criterion = nn.MSELoss()

# 4. Training Loop
print("Starting LSGAN Training...")

dataset = torch.utils.data.TensorDataset(real_data)
loader = torch.utils.data.DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

for epoch in range(EPOCHS):
    for batch_idx, (real,) in enumerate(loader):
        batch_size = real.shape[0]
        real = real.to(device)

        # Train Discriminator
        noise = torch.randn(batch_size, NOISE_DIM).to(device)
        fake = ls_gen(noise)

        disc_real = ls_disc(real).view(-1)
        loss_d_real = criterion(disc_real, torch.ones_like(disc_real))

        disc_fake = ls_disc(fake.detach()).view(-1)
        loss_d_fake = criterion(disc_fake, torch.zeros_like(disc_fake))

        loss_disc = 0.5 * (loss_d_real + loss_d_fake)

        ls_disc.zero_grad()
        loss_disc.backward()
        opt_disc.step()

        # Train Generator
        output = ls_disc(fake).view(-1)
        loss_gen = criterion(output, torch.ones_like(output))

        ls_gen.zero_grad()
        loss_gen.backward()
        opt_gen.step()

    if epoch % 500 == 0:
        print(f"Epoch [{epoch}/{EPOCHS}] Loss D: {loss_disc.item():.4f}, Loss G: {loss_gen.item():.4f}")

# 5. Generate and Save Data
num_synthetic = 20000
with torch.no_grad():
    noise = torch.randn(num_synthetic, NOISE_DIM).to(device)
    ls_fake_data = ls_gen(noise).cpu().numpy()

df_lsgan = pd.DataFrame(ls_fake_data, columns=data.columns)
df_lsgan['Class'] = 1
df_lsgan.to_csv('lsgan_fraud.csv', index=False)
print("Finished. Synthetic data saved to 'lsgan_fraud.csv'.")

#evaluation
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix, RocCurveDisplay

# 1. Load All Data Sources
print("Loading data...")
# Load Original Data (Re-load to ensure we have labels correct)
df_real = pd.read_csv('creditcard.csv')
df_real = df_real.drop(['Time'], axis=1) # Drop Time like before

# Load Scaler to ensure consistency (optional if we just use raw for RF,
# but better to stick to the processed version if possible.
# For Random Forest, scaling isn't strictly necessary, but let's be consistent.)
# Actually, let's stick to the raw CSV for the REAL data to avoid confusion,
# but we must inverse-transform the synthetic data to match the original scale
# OR transform original to scaled.
# EASIEST PATH: Use the Scaled CSVs we created in Step 1.
df_fraud_real = pd.read_csv('X_fraud.csv')
df_legit_real = pd.read_csv('X_legit.csv')

# Load Synthetic Data
df_vanilla = pd.read_csv('vanilla_gan_fraud.csv')
df_wgan = pd.read_csv('wgan_fraud.csv')

# Add labels back (Labels were dropped in X_fraud/X_legit CSVs?)
# In Step 1, X_fraud was just features. Let's add class "1" back.
df_fraud_real['Class'] = 1
df_legit_real['Class'] = 0

# Combine to make the Full Processed Dataset
df_full_scaled = pd.concat([df_legit_real, df_fraud_real])

# 2. Split into Train and Test
# We MUST test on real data only.
X = df_full_scaled.drop('Class', axis=1)
y = df_full_scaled['Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"Test Set Size: {len(y_test)} (This remains constant for all models)")

# 3. Define Helper to Train and Evaluate
def evaluate_model(X_tr, y_tr, name):
    print(f"\n--- Training Classifier on {name} ---")
    print(f"Training Size: {len(X_tr)} (Fraud cases: {sum(y_tr)})")

    # Random Forest is robust and quick
    rf = RandomForestClassifier(n_estimators=50, random_state=42, n_jobs=-1)
    rf.fit(X_tr, y_tr)

    # Predict on the constant TEST set
    y_pred = rf.predict(X_test)
    y_prob = rf.predict_proba(X_test)[:, 1]

    # Metrics
    print(classification_report(y_test, y_pred, target_names=['Legit', 'Fraud']))
    auc = roc_auc_score(y_test, y_prob)
    print(f"AUC-ROC: {auc:.4f}")

    # Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(5, 4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.title(f'Confusion Matrix: {name}')
    plt.ylabel('Actual')
    plt.xlabel('Predicted')
    plt.savefig(f'cm_{name.replace(" ", "_")}.png')
    plt.show()

    return rf

# 4. Scenario 1: Original Imbalanced Data
model_orig = evaluate_model(X_train, y_train, "Original Imbalanced")

# 5. Scenario 2: Vanilla GAN Augmented
# Mix X_train with Synthetic Vanilla
# We strictly use the synthetic data to AUGMENT the training set
X_train_vanilla = pd.concat([X_train, df_vanilla.drop('Class', axis=1)])
y_train_vanilla = pd.concat([y_train, df_vanilla['Class']])

model_vanilla = evaluate_model(X_train_vanilla, y_train_vanilla, "Vanilla GAN Augmented")

# 6. Scenario 3: WGAN Augmented
X_train_wgan = pd.concat([X_train, df_wgan.drop('Class', axis=1)])
y_train_wgan = pd.concat([y_train, df_wgan['Class']])

model_wgan = evaluate_model(X_train_wgan, y_train_wgan, "WGAN Augmented")
# Load LSGAN Data
df_lsgan = pd.read_csv('lsgan_fraud.csv')

# 7.Scenario 4: LSGAN Augmented
X_train_lsgan = pd.concat([X_train, df_lsgan.drop('Class', axis=1)])
y_train_lsgan = pd.concat([y_train, df_lsgan['Class']])

model_lsgan = evaluate_model(X_train_lsgan, y_train_lsgan, "LSGAN Augmented")

# 7. Visualization of Generated Data vs Real Data
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd # Ensure pandas is imported for read_csv

# Load necessary dataframes directly for this visualization cell
# This assumes 'X_fraud.csv' and 'wgan_fraud.csv' have been created by preceding cells.
# If not, this will still raise FileNotFoundError until those cells are fixed and run.
try:
    df_fraud_real = pd.read_csv('X_fraud.csv')
    # Add class label back if it was removed in X_fraud.csv (as done in evaluation cell)
    df_fraud_real['Class'] = 1
except FileNotFoundError:
    print("Warning: X_fraud.csv not found. Please ensure the preprocessing cell (-uhxuHMOTvBB) has run successfully.")
    df_fraud_real = pd.DataFrame() # Create an empty dataframe to prevent further errors

try:
    df_wgan = pd.read_csv('wgan_fraud.csv')
except FileNotFoundError:
    print("Warning: wgan_fraud.csv not found. Please ensure the WGAN training cell (0Q_8rmz4hLZ3) has run successfully.")
    df_wgan = pd.DataFrame() # Create an empty dataframe to prevent further errors


# Select a few features to compare
features_to_plot = ['V12', 'V14', 'V17', 'Amount']

plt.figure(figsize=(15, 10))

for i, feature in enumerate(features_to_plot):
    plt.subplot(2, 2, i+1)

    # Plot Real Fraud Data
    if not df_fraud_real.empty and feature in df_fraud_real.columns: # Only plot if data is loaded and feature exists
        sns.kdeplot(df_fraud_real[feature], label='Real Fraud', fill=True, color='blue', alpha=0.3)
    else:
        plt.text(0.5, 0.5, f'Real Fraud data ({feature}) not loaded/available', horizontalalignment='center', verticalalignment='center', transform=plt.gca().transAxes)


    # Plot WGAN Synthetic Data
    # Note: We limit to first 1000 samples for cleaner plots if data is huge
    if not df_wgan.empty and feature in df_wgan.columns: # Only plot if data is loaded and feature exists
        sns.kdeplot(df_wgan[feature][:1000], label='WGAN Synthetic', fill=True, color='red', alpha=0.3)
    else:
        plt.text(0.5, 0.2, f'WGAN Synthetic data ({feature}) not loaded/available', horizontalalignment='center', verticalalignment='center', transform=plt.gca().transAxes)

    plt.title(f'Distribution of {feature}: Real vs WGAN')
    plt.legend()

plt.tight_layout()
plt.savefig('distribution_comparison.png')
plt.show()

print("Comparison plots saved as 'distribution_comparison.png'. Include this in your report!")